# Site settings
title: Kira's Blog
email:
description: > # this means to ignore newlines until "baseurl:"
  My super sweet blog.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  kirakirakira

# Build settings
markdown: kramdown
kramdown:
    input: GFM
